In [1]:
from ml_utils import Pipeline
import pandas as pd
import numpy as np

C:\Program Files\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
C:\Program Files\Anaconda3\lib\site-packages\sklearn\grid_search.py:42: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. This module will be removed in 0.20.
  DeprecationWarning)

In [2]:
pipeline = Pipeline()
df = pipeline.load_chunk()

df.tail()

Connected to evictions DB.
Set schema to 'evictions'.
Set background cursor.
(189970, 'CA', '060133270005', 2001, '3270.5', 'Contra Costa County, California', 1360.0, 11.84, 10.36, 1630.0, 61806.0, 625000.0, 80.3, 85.81, 0.44, 8.97, 0.66, 2.28, 0.37, 1.47, 0.0, 72.0, 5.0, 5.0, 6.92, 6.92, False, False, '06', '06013', '06013327000', '060133270005', 2001, 0, 1)

,_id,state_code,geo_id,year,name,parent_location,population,poverty_rate,pct_renter_occupied,median_gross_rent,...,eviction_filing_rate,imputed,subbed,state,county,tract,geo_id (repeated),year (repeated),top20_evictions,top20_eviction_rate
995,254321,CA,060375358023,2002,5358.02.3,"Los Angeles County, California",1692.91,14.83,32.88,828.59,...,2.48,False,False,06,06037,06037535802,060375358023,2002,0,0
996,254393,CA,060375359011,2004,5359.01.1,"Los Angeles County, California",1099.00,2.27,16.23,850.00,...,0.00,False,False,06,06037,06037535901,060375359011,2004,0,0
997,254470,CA,060375360001,2001,5360.1,"Los Angeles County, California",989.60,21.82,78.11,530.78,...,2.15,False,False,06,06037,06037536000,060375360001,2001,0,0
998,254481,CA,060375360002,2002,5360.2,"Los Angeles County, California",2864.00,21.26,65.59,622.00,...,1.30,False,False,06,06037,06037536000,060375360002,2002,0,0
999,254517,CA,060375361023,2008,5361.02.3,"Los Angeles County, California",1085.87,0.00,22.59,1342.84,...,0.00,False,False,06,06037,06037536102,060375361023,2008,0,0

In [4]:

# define models to run
models_to_run=['RF','LR', 'NB', 'GB', 'DT', 'KNN'] #'SVM'
# select features to use
features  =  ['geo_id', 'population', 'evictions', 'eviction_filings', 'eviction_filing_rate', 'renter_occupied_households']

classifiers, params = pipeline.get_classifiers()
df = pipeline.fill_missing(df)

X = df[features]
y = df['top20_eviction_rate']

results_df = pipeline.classify(models_to_run, classifiers, params, X,y)


# save to csv
#results_df.to_csv('results.csv', index=False)
results_df

Running through model RF...
Running through model LR...
Running through model NB...
Running through model GB...
Running through model DT...
Running through model KNN...

,model_type,clf,parameters,auc-roc,p_at_5,p_at_10,p_at_20
0,RF,"(DecisionTreeClassifier(class_weight=None, cri...","{'max_depth': 1, 'max_features': 'sqrt', 'min_...",0.959097,1.000000,0.56,0.76
1,LR,"LogisticRegression(C=0.01, class_weight=None, ...","{'C': 0.01, 'penalty': 'l1'}",0.996149,1.000000,1.00,0.82
2,NB,GaussianNB(priors=None),{},0.512779,0.000000,0.20,0.24
3,GB,([DecisionTreeRegressor(criterion='friedman_ms...,"{'learning_rate': 0.1, 'max_depth': 1, 'n_esti...",0.954312,0.916667,0.52,0.72
4,DT,"DecisionTreeClassifier(class_weight=None, crit...","{'criterion': 'gini', 'max_depth': 1, 'min_sam...",0.914868,1.000000,0.80,0.70
5,KNN,"KNeighborsClassifier(algorithm='auto', leaf_si...","{'algorithm': 'auto', 'n_neighbors': 5, 'weigh...",0.667873,0.416667,0.28,0.32